language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script:
  - mkdir build
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=./test/bootstrap.php ./src/ ./test/
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml   

